# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build Stride Docs v2 for Azure Web App stride-docs-test

on:
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - 'README.md'
  #     - 'wiki/**'
  #     - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    - name: Checkout Stride Docs
      uses: actions/checkout@v3
      with:
        path: stride-docs

#     - name: Checkout Stride (note the LFS)
#       uses: actions/checkout@v3
#       with:
#         repository: stride3d/stride
#         token: ${{ secrets.GITHUB_TOKEN }}
#         path: stride
#         lfs: true

#     - name: Install DocFX
#       run: dotnet tool update -g docfx
# #      - run: dotnet tool install -g docfx --version 2.65.1

#     - name: Build documentation
#       run: ./build-all.bat
#       working-directory: stride-docs

    - name: Compress artifact
      run: 7z a -r DocFX-app.zip ./stride-docs/en/*

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: DocFX-app
        path: DocFX-app.zip

  deploy:
    runs-on: windows-2022
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: DocFX-app

      - name: List current directory
        run: ls

      - name: Decompress artifact
        run: 7z x DocFX-app.zip -o./stride-docs/_site

      # - name: Deploy to Azure Web App
      #   id: deploy-to-webapp
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: 'stride-docs-test'
      #     slot-name: 'Production'
      #     publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_32FCD402B970463A9143B24C9B225749 }}
      #     package: ./stride-docs/_site